# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.synced_folder "../../../", "/home/quran", type: "rsync"

  config.vm.provider :aws do |aws, override|
    aws.region = 'us-west-2'
    aws.instance_type = "t2.micro"
    aws.access_key_id = "AKIAJW3G4K3NGQSBY2GA"
    aws.secret_access_key = "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"
#    aws.session_token = "SESSION TOKEN"
    aws.keypair_name = "awskey"

    aws.ami = "ami-9abea4fb" # Ubuntu Server 14.04 LTS (HVM), SSD Volume Type

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/home/vagrant/awskey.pem"
    override.nfs.functional = false # workaround for folder sharing not working
  end

  config.vm.provision "shell", path: "./provisioner.sh", args: "quranfalweb" #, run: "always"
end
