# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quranfal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraya',
            name='list',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userword',
            name='list',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.DistinctWord'),
        ),
    ]
