# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0009_word_utextmin'),
        ('quranfal', '0002_auto_20160608_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='useraya',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranfal.List'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranfal.List'),
        ),
        migrations.AddField(
            model_name='list',
            name='ayas',
            field=models.ManyToManyField(through='quranfal.UserAya', to='quran.Aya'),
        ),
        migrations.AddField(
            model_name='list',
            name='words',
            field=models.ManyToManyField(through='quranfal.UserWord', to='quran.DistinctWord'),
        ),
    ]
