# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranfal', '0003_auto_20160608_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='ayas',
            field=models.ManyToManyField(related_name='lists', through='quranfal.UserAya', to='quran.Aya'),
        ),
        migrations.AlterField(
            model_name='list',
            name='words',
            field=models.ManyToManyField(related_name='lists', through='quranfal.UserWord', to='quran.DistinctWord'),
        ),
        migrations.AlterField(
            model_name='useraya',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userword',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
