# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quranfal', '0008_list_table_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraya',
            name='aya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ayas', to='quran.Aya'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='distinct_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='quran.DistinctWord'),
        ),
    ]
